//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTraning
{
    using System;
    using System.Collections.Generic;
    
    public partial class 基金非營業日統計_luann
    {
        public string 非營業日 { get; set; }
        public string 公司代號 { get; set; }
        public Nullable<byte> 基金總數 { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<long> MTIME { get; set; }
    }
}
