//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTraning
{
    using System;
    using System.Collections.Generic;
    
    public partial class 日期貨盤後行情表_luann
    {
        public string 交易日期 { get; set; }
        public string 契約 { get; set; }
        public string 到期月份_週別_ { get; set; }
        public Nullable<decimal> 開盤價 { get; set; }
        public Nullable<decimal> 最高價 { get; set; }
        public Nullable<decimal> 最低價 { get; set; }
        public Nullable<decimal> 收盤價 { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<long> MTIME { get; set; }
    }
}
