//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTraning
{
    using System;
    using System.Collections.Generic;
    
    public partial class 股東會投票日明細_luann
    {
        public string 投票日期 { get; set; }
        public string 證券代號 { get; set; }
        public string 證券名稱 { get; set; }
        public string 召集人 { get; set; }
        public string 股東會日期 { get; set; }
        public string 發行代理機構 { get; set; }
        public string 聯絡電話 { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<long> MTIME { get; set; }
    }
}
